# System Post task - E.g. Check os_family, os distribution, memory, cpu, available disk space etc.

# Include common variable file.
- include_vars: "roles/common/vars/main.yml"

# Post TASK
# System_verify_TASKS, e.g. Gather evidance, delete temp directories when distribution is CentOS
- block:
    - name: "_Post TASK: test1 - List dir {{ temp_dir }}  - dir "
      shell: /usr/bin/uptime
      register: result
      tags: post_task

    - debug:
        var: result
        verbosity: 2

    - name: "_Post TASK: Delete {{ temp_dir }}  - dir "
      file: path="{{ temp_dir }}" state=absent
      tags: post_task


# Gather_Evidance TASK
#- block:
    #- name: "_Post TASK: Gather Evidance {{ temp_dir }}  - dir "

#    - debug:
#        var: result
#        verbosity: 1
#      tags: post_task

